export const articleReview = [
  {
    id: 1,
    company: "Jasper theraputic inc.",
    title: "this is title",
    indication: "AML",
    newswire_sites: "globalnewswire",
    asset: "JSP191",
    phase: "phase-1",
    scrapped_date: "Mar-31-2022",
    status: "approved",
  },
  {
    id: 2,
    company: "Lava theraputic inc.",
    title: "this is title2",
    indication: "AML",
    newswire_sites: "prnewswire",
    asset: "LAVA-051",
    phase: "phase-12",
    scrapped_date: "Mar-30-2022",
    status: "approved",
  },
  {
    id: 3,
    company: "Lava theraputic inc.",
    title: "this is title2",
    indication: "AML",
    newswire_sites: "prnewswire",
    asset: "LAVA-051",
    phase: "phase-12",
    scrapped_date: "Mar-30-2022",
    status: "approved",
  },
];
