export const BullseyaData = [
  {
    Modalities: "Other cell therapies: TCR",
    Asset: "MB-dNPM1-TCR.1",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Fusion proteins",
    Asset: "Angiocidin",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "MYB",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor: oxidative phosphorylation",
    Asset: "IACS-010759",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Protein degraders",
    Asset: "TRIB1",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "BI-894999",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "GSK 1324726A (I-BET726)",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "DNA inhibitors: albumin-encapsulated 8-chloro-adenosine",
    Asset: "JNTX-104",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: (aAVC formulation loaded with WT1)",
    Asset: "ASP7517",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "ADC",
    Asset: "MBK-101",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "PTX-200",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: Allogeneic GDTs",
    Asset: "TCB002",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Zantrene (bisantrene)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Liposomal Annamycin",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "PEG-BCT-100",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Pegcrisantaspase",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "AZD6738 (Ceralasertib)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Alisertib",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "AZD2811",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Bemcentinib (BGB-324)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Dubermatinib (TP-0903)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "ONO-7475",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "SKI-G-801",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "S65487",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Venclexta (Venetoclax)",
    Phase: "Approved",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "APG2575",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "ZN-d5",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "BP1002",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "S-55746",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Iclusig (Ponatinib)",
    Phase: "Approved",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "ABBV-744",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "Mivebresib (ABBV-075)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "PLX2853",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "JAB-8263",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "BPI-23314",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "CFT-743",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "FT-1101",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "AB8939",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "PLX51107",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "NUV-868",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "CDX bi-specific antibodies",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Ibrutinib",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor: (peptide inhibitor)",
    Asset: "ST-101",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "12328zT2",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "123BBzT2",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "3328zT2",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "33BBzT2",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "HRAIN-007",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CAR T",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: LV T cell ",
    Asset: "LV-T cell CAR T",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Allogeneic ?? CAR T",
    Asset: "TCB004",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "M-ceNK",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "IM23 CAR-T ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "JSP191",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "Anti-CD123 CAR-T",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CAR-T ",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CART123 cells + Lymphodepletion therapy",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CD123 CAR-T",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CD-123 CAR-T",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CD123 CAR-T cells",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CD123-CAR T ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "ADC",
    Asset: "IMGN632",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "UCART123",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "UniCAR-T-CD123",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb DART",
    Asset: "Flotetuzumab",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "Vibecotamab (XmAb14045)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb DuoBody",
    Asset: "JNJ-63709178",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "SAR440234",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb ADAPTIR",
    Asset: "APVO436",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "MB-102",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CD123 CAR T",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: Cell therapy using a SparX protein",
    Asset: "ACLX-002",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Autologous",
    Asset: "HY-007",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CART-19",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "ADC",
    Asset: "NV-102",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "ADC",
    Asset: "Adcetris (brentuximab vedotin)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "OmniCAR CD33 & CLL-1",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Actimab-A (Lintuzumab-Ac225) ",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BiTE",
    Asset: "AMG 330",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BiTE",
    Asset: "AMG 673",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "TCE: Bivalent BsAb",
    Asset: "AMV-564",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CAR33VH",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CD123-CD33 cCAR",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CD33",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CD33 CAR-T",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CLL-1, CD33 and CD123-CAR T cells",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Autologous compound CAR T",
    Asset: "CLL1-CD33 cCAR (ICG-144)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Allogeneic ",
    Asset: "CRISPR edited CD33 CAR T",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "GEM333",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "NKE: Tri-specific",
    Asset: "GTB-3550",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "NKE: Tri-specific",
    Asset: "GTB-C3550",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "huCD33-BsAb",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "ADC",
    Asset: "Mylotarg (gemtuzumab)",
    Phase: "Approved",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Autologous ",
    Asset: "PRGN-3006",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "JNJ-67571244",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities:
      "Other cell therapies: allogeneic CRISPR/Cas9 genome-edited HSPC therapy",
    Asset: "VCAR33",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "DARIC33",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "DARIC NextGEN",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "ADC",
    Asset: "BVX-001",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Autologous",
    Asset: "LB-1910",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Allogeneic ",
    Asset: "CB-012",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Daratumumab",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Isatuximab ",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "ADC",
    Asset: "EDC8",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: " AT-1413",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Iomab-B",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "ALX148",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "C47B157, C47B161 and C47B222 ",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "ES004",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "IBI188 (Letaplimab)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Lemzoparlimab (TJC4; TJ011133)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Magrolimab (Hu5F9-G4)",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "TTI-621",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "TTI-622 ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "TTI-622 ",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "AO-176 ",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Yttrium-90",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Cusatuzumab",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "SEA-CD70",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Allogeneic ",
    Asset: "ALLO-316",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "ACE-1975",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "INA03",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "LBS-007",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Dinaciclib (MK7965) ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "FN-1501",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Fadraciclib (CYC065)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Palbociclib",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "YPN 005",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "SEL120",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Alvocidib",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "AZD4573",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Sunaciclib",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Voruciclib",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "VIP152 (BAY 1251152)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic CAR NK",
    Asset: "CYTO T-101",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Autologous",
    Asset: "TAA5-CAR-T",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Allogeneic ",
    Asset: "TAA3-UCAR-T",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Protein degraders",
    Asset: "Lenalidomide",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Protein degraders",
    Asset: "BTX-508 (PHM�-based PROTACs)",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Protein degraders",
    Asset: "BTX-A51 (BTX-1188)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "TCE: Tripe antigen",
    Asset: "ALETA-004",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CLL-1.CAR T cells ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Autologous",
    Asset: "KITE-222",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic CAR NK",
    Asset: "ONKT104",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "CU04",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "JNJ-40346527",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Ipilimumab",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Tipifarnib",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Dociparstat (CX-01)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "SX-682",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "LY2510924",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Motixafortide (BL-8040)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "GP 01CR01",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "DNA inhibitors",
    Asset: "DFP-10917",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Brequinar",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "JNJ-74856665",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "PTC299",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "RP-7214",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "DNA inhibitors",
    Asset: "Vyxeos (CPX-351)",
    Phase: "Approved",
    Indications: "AML",
  },
  {
    Modalities: "DNA inhibitors",
    Asset: "BST-236 (Aspacytarabine)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "DNA inhibitors",
    Asset: "Nedisertib",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "ASTX-727",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "Guadecitabine",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "Sapacitabine",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "ASTX030",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "NTX-301",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "ONC201",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Pinometostat",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators, Kinase inhibitors",
    Asset: "APL-581",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators, Kinase inhibitors",
    Asset: "NEO-2734",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Protein degraders",
    Asset: "ASTX660",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies",
    Asset: "VOR33",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Fusion proteins",
    Asset: "SEPHB4-HAS",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "AZD-0364 (ATG-017)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "BVD-523",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "LY3214996 ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Uproleselan (GMI-1271)",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "GMI-1687",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Selinexor (KPT-330)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "Valemetostat (DS-3201b)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "FLYSYN-101",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "AMG 427",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "AMG 553",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "ASP1235 (AGS62P1)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Crenolanib",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "FF-10101-01",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Xospata (Gilteritinib)",
    Phase: "Approved",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "HM43239",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Rydapt (Midostaurin)",
    Phase: "Approved",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "PLX3397",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Quizartinib",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "SKLB1028",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Chrysoeriol (Cresorol)",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Clifutinib",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "HYML-122",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "JRF-104",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "KIN-4104",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "LT-171-861 ",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "MRX-2843",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "ON-150030",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "SAR-20293",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "ALLO-819",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "PHI-101",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "ETH-155008",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "CLN-049",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Mivavotinib/TAK-659 + Ninlaro (Ixazomib)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "MAX-40279",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "NMS-03592088",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies",
    Asset: "TEG001",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: Allogenic blood derived ?? T Cells",
    Asset: "GDX-012",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "TCE: ?? BsAb",
    Asset: "LAVA-051",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "CB-839 ",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Telaglenastat (CB-839) ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "ONC212",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: Antisense Oligonucleotide",
    Asset: "Prexigebersen (BP1001) ",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: Cell Therapy (HSC derived)",
    Asset: "MGTA-456",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Entinostat",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Panobinostat",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Pracinostat",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Vorinostat",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "OM-301 (PNC-27)",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities:
      "Small molecule inhibitor:  anti-nucleolin histone methyltransferase (HMT) aptamer-nucleoside drug conjugate",
    Asset: "APTA-16 (SJP1604 )",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "Onureg (CC-486)",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Pitavastatin",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor: (peptide inhibitor)",
    Asset: "Nerofe",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small mloecule inhibitor",
    Asset: "Minnelide",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small mloecule inhibitor",
    Asset: "LAM-003",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "PU-H71",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Olutasidenib (FT-2102)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Tibsovo (Ivosidenib)",
    Phase: "Approved",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "BAY1436032",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "AB-218",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "HMPL-306",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Idhifa (Enasidenib, AG-221)",
    Phase: "Approved",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "SH-1573",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Fusion proteins",
    Asset: "Inbakicept (ALT 803) ",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Fusion proteins",
    Asset: "Tagraxofusp (SL-401)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Protein degraders: IMiD",
    Asset: "Pomalidomide",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "DCP-001",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Fusion proteins",
    Asset: "Teleukin (F16IL2)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "DNA inhibitors",
    Asset: "FF-10501-01",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Indoximod",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: iPSC-derived NK",
    Asset: "FT538",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "CA-4948",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Ruxolitinib",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Devimistat (CPI-613)",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "ILT3",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "IO-202",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Bomedemstat (IMG-7289)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor: dual",
    Asset: "Domatinostat (4SC-202)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "HM-97211, HM97278, HM97293",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Iadademstat (ORY-1001)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor:  dual",
    Asset: "JBI-802",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "CPI-482",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "RASP-201",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "seclidemstat",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "T-3775440",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "TAS-1440",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "TPC-144",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Tranylcypromine (TCP)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "BMS-90011, CC-90011",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Tranylcypromine",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "AMG 176",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "AMG 397",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "AZD5991 ",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "S64315",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "PRT1419",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "ABBV-467",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "ALRN-6924",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "AMG 232 (KRT 232)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "APG-115",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "ASTX295",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Milademetan (RAIN-32, DS-3032)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Siremadlin (HDM201)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Binimetinib (MEK 162)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Cobimetinib",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "OTS167",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "ARN-0953",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "DS-1594",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "JNJ-75276617",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "SNDX-5613",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "KO-539",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modualtors: RNA methyltransferase inhibitors",
    Asset: "METTL3",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "DNA inhibitors",
    Asset: "Karonudib",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Sirolimus",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "GO-203-2c",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: T-cell therapy",
    Asset: "Mana-312",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: T-cell therapy",
    Asset: "Mana-412",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Ningetinib",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Regorafenib",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Nintedanib (BIBF 1120)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "APTO-253",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Pevonedistat ",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "CIML NK cells",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "FATE-NK100",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: iPSC-derived NK",
    Asset: "FT516",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "CYNK-001 (taniraleucel)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: NK Cell Therapy",
    Asset: "INKmune",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "K-NK002",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "K-NK003",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "WU-NK-101",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic CAR NK",
    Asset: "CYTO NK-201",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: RBCs based",
    Asset: "RTX-240",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic CAR NK",
    Asset: "SENTI-202",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset:
      "Haploidentical NK cells + HSCT conditioning regimen + HSCT + Cyclophosphamide + GvHD prophylaxis ",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "NK Cells",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "NK cells + Haploidentical Bone Marrow Transplant",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CYAD-02",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic CAR NK",
    Asset: "NKX101",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "RASP-301 (TES-2169)",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "mAb: neutralizing antibody ",
    Asset: "HFB2009 ",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "DNA inhibitors: (Aptamer Linked Anti Nucleolin)",
    Asset: "QN-247",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR NK or NK cell therapies: Allogeneic NK Cells",
    Asset: "GTA002",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "PF-04518600",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "CCS1477",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "APR-548",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Eprenetapopt (APR-246)",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Kevetrin (Thioureidobutyronitrile)",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "CB-5339 ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "CG-202",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Luxeptinib (CG-806)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "LY2874455",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Lynparza (Olaparib)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Talzenna (Talazoparib)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Veliparib",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "mAb: Checkpoint inhibitor",
    Asset: "Spartalizumab (PDR001) ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "mAb: Checkpoint inhibitor",
    Asset: "Nivolumab",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "mAb: Checkpoint inhibitor",
    Asset: "Keytruda (Pembrolizumab)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "mAb: Checkpoint inhibitor",
    Asset: "Durvalumab ",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "mAb: Checkpoint inhibitor",
    Asset: "Atezolizumab",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Apoptosis stimulant",
    Asset: "RP-323",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Apoptosis stimulant",
    Asset: "KPC-34",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "AUM-302 (IBL-202)",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "HSB-510",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "LGH447",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "SEL24 (MEN1703)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "INCB053914",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "CYC140",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Onvansertib",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "Rigosertib ",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "CFI-400945",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Hu8F4",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: PRAME-TCR Therapy",
    Asset: "BPX-701",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "GSK3326595",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Velcade (Bortezomib)",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Ixazomib (MLN 9708)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "TK216",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Tamibarotene (SY-1425)",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "TAS1553",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "ADC",
    Asset: "VLS-101",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "H3B-8800",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Fusion proteins",
    Asset: "DSP-107",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Daurismo (glasdegib) ",
    Phase: "Approved",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "OPB-111077",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: Stem Cell Neoantigens",
    Asset: "PACTN (Personalized Adoptive Cellular Therapy)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "ABBV-184",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors",
    Asset: "Entospletinib (GS-9973)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: Allogenic T-cell therapy",
    Asset: "SMART 101 ",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "CD123 X CD3",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: T-cell therapy",
    Asset: "PDS-0102",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: T-cell therapy",
    Asset: "TAA-T Lymphocytes",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: T-cell therapy",
    Asset: "HA-1 specific T cell TCR therapy",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: T-cell therapy",
    Asset: "NEXI-001",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: T-cell therapy",
    Asset: "DNT UHN-1 T-Cells",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: T-cell therapy",
    Asset: "Multi Tumor Associated Antigen (TAA)-Specific T Cells",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies: T-cell therapy",
    Asset: "MDG1011 ",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "Sabatolimab (MBG453)",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "mAb",
    Asset: "SHR-1702",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "TL-895 ",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Apoptosis stimulant",
    Asset: "Eftozanermin alfa (ABBV-621)",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "DNA inhibitors",
    Asset: "Vosaroxin",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors: TKI",
    Asset: "Nilotinib",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Protein degraders",
    Asset: "CC-90009",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities:
      "Other cell therapies: CD34+ cord-blood derived hematopoietic progenitor cells plus genetically-modified endothelial cells",
    Asset: "AB-110",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "ABD-3001",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor: Undisclosed",
    Asset: "Unnamed",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "Vaccine",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor: Undisclosed",
    Asset: "Unnamed",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor: Undisclosed",
    Asset: "Unnamed",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Antroquinonol",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts: Autologous",
    Asset: "ATA2321",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors",
    Asset: "EP0042",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "HP537",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "TCE: Tripe antigen",
    Asset: "KJ-102",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "LP-118",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "ADC",
    Asset: "RD130",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "TCE: BsAb",
    Asset: "RO7283420",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Epigenetic modulators",
    Asset: "TT-125",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "LP-108",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Kinase inhibitors ",
    Asset: "XY0206",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "DC/AML Fusion Cell Vaccine",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "DC/AML Fusion Cell Vaccine",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "DC/AML Fusion Cell Vaccine",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "GM-K562",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "GVAX Vaccine",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "WT1 mRNA-electroporated DC vaccination",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "WT1/PRAME vaccination",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "TRPH-395",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "CWP291",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "Vaccine",
    Asset: "Galinpepimut-S",
    Phase: "Ph3",
    Indications: "AML",
  },
  {
    Modalities: "Other cell therapies",
    Asset: "NTLA-5001",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "Small molecule inhibitor",
    Asset: "Eltanexor (ATG-016)",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "Haploidentical IL-21-Expanded Natural Killer Cells",
    Phase: "Ph2",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "Dual CD33-CLL1 CAR NK Cells",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "TIM3/CD33 CAR NK cells",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "Triplebody SPM-2",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "Haploid Allogeneic NK cell therapy",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "Zhejiang University NK cells/Combined Monoclonal Antibodies",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "NK cells + Chemotherapy",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "Allogeneic NK cells + Azacitidine",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "Allogeneic NK cells",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "NK cells + Haplo HSCT",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "NK cells",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "NK cells",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "UCB-NK cells",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "Allogeneic NK cells",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "IL-15 stimulation NK cell infusion",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "DVX-201",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "ONK-3010",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "ONK-3020",
    Phase: "Preclinical",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "NK-DLI",
    Phase: "Ph1/2",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "TAA05 ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR Ts",
    Asset: "CD33-CLL1 CAR-T ",
    Phase: "Ph1",
    Indications: "AML",
  },
  {
    Modalities: "CAR-NK or NK cell therapies",
    Asset: "AK117 ",
    Phase: "Ph1/2",
    Indications: "AML",
  },
];
